### ISSUE TITLE
psql relation does not handle roles

### ISSUE THREAD

**Issue by awnns** [canonical/postgresql-operator#300]
In the original psql relation used in the reactive charm, the user can request roles by setting the "roles" field to a comma separated list of desired roles. In this charm, this field is silently ignored, leading the user to scratch his head in frustration.

Proposed solutions:

1. Implement the feature for the legacy interface, or
2. Make it not silent, so that the user understands why he is not getting any roles.

**Comment by dragomirp** [comment]
Hi, @awnns, thank you for the report. We will update this issue when we decide how to proceed with roles in the legacy interface. The new `postgresql_client` interface should already support this, so please take a look to see if it is something that can work for you in the short term.

**Comment by dragomirp** [comment]
Hi, @awnns, due to the legacy interface being deprecated, we decided to make the charm block when roles are requested. We have updated the [documentation](https://charmhub.io/postgresql/docs/e-legacy-charm) to mention that and should update the charm shortly. Please, consider migrating your charms to the new `postgresql_client` interface.

**Comment by dragomirp** [comment]
Hi, latest edge (rev. 350) should block if roles are requested via the legacy interface.
